name: "cms web portal"
triggers:
  github:
    secret: test
    events:
      - eventName: "push"
        filter: 'body.ref in ["refs/heads/tes"]'
    manual_dispatch:
      secret: test
env:
  name: serverless
  age: 2
steps:
  - run: npm i @serverless-devs/s -g --registry=https://registry.npmmirror.com
  - run: s config add --AccountID ${{secrets.account}}  --AccessKeyID ${{secrets.ak}}  --AccessKeySecret ${{secrets.sk}} -a default -f
  - run: npm i --registry=https://registry.npmmirror.com
    working-directory: ./web
  - run: npm run generate
    working-directory: ./web
  - run: s deploy --use-local -y